[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pyright", "ruff"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language.formatter]
command = "black"
args = [
  "-",
  "--quiet",
  "--line-length=88"
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]


[language-server.pyright.config]
reportMissingTypeStubs = false
inlay-hints = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[language-server.zls]
command = "/usr/bin/zls"
config.zig_exe_path = "/usr/bin/zls"

[language-server.vale]
command = "vale.vale-ls"

[[language]]
name = "markdown"
language-servers = ["mdpls", "vale"]

[language-server.mdpls]
command = "/home/ubuntu/.cargo/bin/mdpls"
config = { markdown.preview.auto = true, markdown.preview.browser = "brave" }
